Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

(1 inline comment)

Before this change I have a lot of exceptions:

    Plug-in org.eclipse.mylyn.github.ui was unable to load class org.eclipse.mylyn.github.internal.GitHubRepositoryConnector.
    ...
    Caused by: java.lang.ClassNotFoundException: org.eclipse.mylyn.github.internal.GitHubRepositoryConnector
    ...
    !MESSAGE Plug-in org.eclipse.mylyn.github.ui was unable to load class org.eclipse.mylyn.github.internal.GitHubRepositoryConnector.
    !STACK 0
    java.lang.ClassNotFoundException: org.eclipse.mylyn.github.internal.GitHubRepositoryConnector

In general +1 but after a second 'bin.includes' removed, see comment inline.

Patch-set: 1